include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - flutter_style_todos
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_const
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart 