targets:
  $default:
    builders:
      json_serializable:
        options:
          # 显式包含字段的默认值
          explicit_to_json: true
          # 生成的代码会使用checked参数来进行类型检查
          checked: true
          # 生成nullable字段
          include_if_null: false
          # 字段重命名策略
          field_rename: none
          # 生成copyWith方法
          create_factory: true
          create_to_json: true 